In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
ls

configs/          README.md         run_neuron_interpret.py  setup.py
log/              recbole_sae/      run_recsae.py            wandb/
log_tensorboard/  requirements.txt  saved/

In [2]:
cd /content/drive/MyDrive/Colab_Notebooks/CIKMv3

/content/drive/MyDrive/Colab_Notebooks/CIKMv3

In [12]:
cd RecBole/

/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole

In [13]:
!pip install -e .

Obtaining file:///content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17.2 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (1.16.3)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (2.2.2)
Requirement already satisfied: tqdm>=4.48.2 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (4.67.3)
Collecting colorlog==4.7.2 (from recbole==1.2.1)
  Downloading colorlog-4.7.2-py2.py3-none-any.whl.metadata (9.9 kB)
Collecting colorama==0.4.4 (from recbole==1.2.1)
  Downloading colorama-0.4.4-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: scikit_learn>=0.23.2 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (1.6.1)
Requirement already satisfied: pyyaml>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (6.0.3)
Requirement already satisfied: tensorboard>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (2.19.0)
Collecting thop>=0.1.1.post2207130030 (from recbole==1.2.1)
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tabulate>=0.8.10 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (0.9.0)
Requirement already satisfied: plotly>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (5.24.1)
Collecting texttable>=0.9.0 (from recbole==1.2.1)
  Downloading texttable-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.12/dist-packages (from recbole==1.2.1) (5.9.5)
Collecting ray>=2.31.0 (from recbole==1.2.1)
  Downloading ray-2.54.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->recbole==1.2.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->recbole==1.2.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->recbole==1.2.1) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.0.0->recbole==1.2.1) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.0.0->recbole==1.2.1) (26.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (8.3.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (3.25.2)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (4.26.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (1.1.2)
Requirement already satisfied: protobuf>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (5.29.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from ray>=2.31.0->recbole==1.2.1) (2.32.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>=0.23.2->recbole==1.2.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit_learn>=0.23.2->recbole==1.2.1) (3.6.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (1.80.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (3.10.2)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (75.2.0)
Requirement already satisfied: six>1.9 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard>=2.5.0->recbole==1.2.1) (3.1.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->recbole==1.2.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.10.0->recbole==1.2.1) (1.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.10.0->recbole==1.2.1) (1.3.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard>=2.5.0->recbole==1.2.1) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.31.0->recbole==1.2.1) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.31.0->recbole==1.2.1) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.31.0->recbole==1.2.1) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema->ray>=2.31.0->recbole==1.2.1) (0.30.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.31.0->recbole==1.2.1) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.31.0->recbole==1.2.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.31.0->recbole==1.2.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->ray>=2.31.0->recbole==1.2.1) (2026.2.25)
Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Downloading colorlog-4.7.2-py2.py3-none-any.whl (10 kB)
Downloading ray-2.54.1-cp312-cp312-manylinux2014_x86_64.whl (72.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 MB 13.4 MB/s eta 0:00:00
Downloading texttable-1.7.0-py2.py3-none-any.whl (10 kB)
Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Installing collected packages: texttable, colorlog, colorama, thop, ray, recbole
  Running setup.py develop for recbole
Successfully installed colorama-0.4.4 colorlog-4.7.2 ray-2.54.1 recbole-1.2.1 texttable-1.7.0 thop-0.1.1.post2209072238

In [3]:
import numpy
print(f'NumPy version: {numpy.__version__}')

NumPy version: 1.26.4

### load trained LightGCN-SAE on movielen-100k (user reps)

In [ ]:
cd ../RecBole-SAE/

/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole-SAE

In [18]:
# Alternatively, if you want to force Llama-3 with an explicit token:
import os
# Uncomment the line below and paste your token if the login cell didn't work
os.environ['HF_TOKEN'] = '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'

In [ ]:
# Training SAE based on LightGCN
!python run_recsae.py \
    --checkpoint saved/LightGCN-Mar-16-2026_23-57-28.pth \
    --item_category "movies" \
    --item_name "movie"

In [ ]:
# Load existing SAE (skip retraining) + interpret
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Mar-16-2026_23-57-28.pth \
    --sae_checkpoint saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth \
    --item_category  movies \
    --top_k 10

01:32:20  INFO      Run: LightGCN-Mar-16-2026_23-57-28   category: movies
01:32:20  INFO      ── Step 1: Loading base model ──────────────────
01:32:24  INFO      NumExpr defaulting to 2 threads.
2026-03-18 01:32:27.040041: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-18 01:32:27.044834: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-18 01:32:27.072580: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1773797547.123010   12677 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1773797547.138875   12677 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1773797547.184172   12677 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773797547.184259   12677 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773797547.184265   12677 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773797547.184270   12677 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-18 01:32:27.196359: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
01:32:35  INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv1/RecBole/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10, 20, 50]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 3
reg_weight = 0.0001
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
01:32:36  INFO      ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
01:32:36  INFO      [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
01:32:36  INFO      [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/model/general_recommender/lightgcn.py:126: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:654.)
  SparseL = torch.sparse.FloatTensor(i, data, torch.Size(L.shape))
01:32:38  INFO      Model=LightGCN uses=944 items=1683  dim=64
01:32:38  WARNING   Item file not found: /content/drive/MyDrive/Colab_Notebooks/CIKMv1/RecBole/recbole/config/../dataset_example/ml-100k/ml-100k/ml-100k.item  (only item_id will be available)
01:32:38  INFO      Item side-info loaded for 1682 items  (fields: ['title'])
01:32:38  INFO      Object saved to ./results/item_side_info.json
01:32:38  INFO      ── Step 2: Loading SAE from saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth ──
01:32:38  INFO      Loaded SAE from saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth  (input=64, latent=1024, k=8)
01:32:38  INFO      SAE latent_dim=1024  k=8
01:32:38  INFO      ── Step 3: Encoding item embeddings through SAE ─
01:32:38  INFO      item_acts shape=(1683, 1024)  non-zero=0.8%
01:32:38  INFO      ── Step 4: Ranking top items per neuron ────────
01:32:38  INFO      Active neurons (≥1 item): 49/1024  (dead: 975)
01:32:38  INFO      ── Step 5: LLM neuron labelling ────────────────
01:32:43  INFO      Loading HF model: meta-llama/Meta-Llama-3-8B-Instruct
01:32:43  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json "HTTP/1.1 200 OK"
01:32:43  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json "HTTP/1.1 200 OK"
config.json: 100% 654/654 [00:00<00:00, 1.85MB/s]
01:32:43  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
`torch_dtype` is deprecated! Use `dtype` instead!
01:32:43  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json "HTTP/1.1 200 OK"
01:32:43  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model.safetensors "HTTP/1.1 404 Not Found"
01:32:44  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model.safetensors.index.json "HTTP/1.1 200 OK"
01:32:44  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model.safetensors.index.json "HTTP/1.1 200 OK"
model.safetensors.index.json: 23.9kB [00:00, 24.3MB/s]
01:32:44  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/revision/main "HTTP/1.1 200 OK"
Downloading (incomplete total...): 0.00B [00:00, ?B/s]
Fetching 4 files:   0% 0/4 [00:00<?, ?it/s]01:32:44  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2/model-00001-of-00004.safetensors "HTTP/1.1 302 Found"
01:32:44  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2/model-00004-of-00004.safetensors "HTTP/1.1 302 Found"
01:32:44  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2/model-00003-of-00004.safetensors "HTTP/1.1 302 Found"
01:32:44  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2/model-00002-of-00004.safetensors "HTTP/1.1 302 Found"
01:32:44  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/xet-read-token/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2 "HTTP/1.1 200 OK"
Downloading (incomplete total...):   0% 0.00/4.92G [00:00<?, ?B/s]01:32:44  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/xet-read-token/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2 "HTTP/1.1 200 OK"
Downloading (incomplete total...):   0% 0.00/9.92G [00:00<?, ?B/s]01:32:44  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/xet-read-token/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2 "HTTP/1.1 200 OK"
Downloading (incomplete total...):   0% 0.00/11.1G [00:00<?, ?B/s]01:32:44  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/xet-read-token/8afb486c1db24fe5011ec46dfbe5b5dccdb575c2 "HTTP/1.1 200 OK"
Downloading (incomplete total...): 100% 16.1G/16.1G [15:08<00:00, 24.6MB/s]
Fetching 4 files: 100% 4/4 [15:08<00:00, 227.16s/it]
Download complete: 100% 16.1G/16.1G [15:08<00:00, 17.7MB/s]
Loading weights: 100% 291/291 [00:01<00:00, 162.40it/s, Materializing param=model.norm.weight]
01:47:55  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/generation_config.json "HTTP/1.1 200 OK"
01:47:55  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/generation_config.json "HTTP/1.1 200 OK"
generation_config.json: 100% 187/187 [00:00<00:00, 832kB/s]
01:47:55  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
01:47:55  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 200 OK"
tokenizer_config.json: 51.0kB [00:00, 95.8MB/s]
01:47:55  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
01:47:55  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
01:47:55  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer.json "HTTP/1.1 200 OK"
01:47:55  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer.json "HTTP/1.1 200 OK"
tokenizer.json: 9.09MB [00:00, 23.7MB/s]
01:47:55  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer.model "HTTP/1.1 404 Not Found"
01:47:55  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
01:47:56  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/special_tokens_map.json "HTTP/1.1 200 OK"
01:47:56  INFO      HTTP Request: GET https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/special_tokens_map.json "HTTP/1.1 200 OK"
special_tokens_map.json: 100% 73.0/73.0 [00:00<00:00, 249kB/s]
01:47:56  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
01:47:58  INFO      HTTP Request: GET https://huggingface.co/api/models/meta-llama/Meta-Llama-3-8B-Instruct "HTTP/1.1 200 OK"
The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=32) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
02:00:08  INFO        [1/49] neuron    1 → "Classic Sci-Fi Movies"
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=32) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole-SAE/run_neuron_interpret.py", line 618, in <module>
    main()
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole-SAE/run_neuron_interpret.py", line 533, in main
    raw   = llm.chat(messages, max_new_tokens=32)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole-SAE/run_neuron_interpret.py", line 293, in chat
    out = self._pipe(
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/text_generation.py", line 293, in __call__
    return super().__call__(text_inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/base.py", line 1274, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/base.py", line 1281, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/base.py", line 1173, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/text_generation.py", line 397, in _forward
    output = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py", line 2669, in generate
    result = decoding_method(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py", line 2874, in _sample
    outputs = model_forward(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py", line 835, in wrapper
    output = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/llama/modeling_llama.py", line 486, in forward
    outputs: BaseModelOutputWithPast = self.model(
                                       ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py", line 1002, in wrapper
    outputs = func(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/llama/modeling_llama.py", line 421, in forward
    hidden_states = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/modeling_layers.py", line 93, in __call__
    return super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1787, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/llama/modeling_llama.py", line 335, in forward
    hidden_states = self.mlp(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1776, in _wrapped_call_impl

In [ ]:
# Load existing SAE (skip retraining) + interpret
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Mar-16-2026_23-57-28.pth \
    --sae_checkpoint saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth \
    --item_category  movies \
    --top_k 10 \
    --llm_model "HuggingFaceTB/SmolLM2-1.7B-Instruct"

02:13:07  INFO      Run: LightGCN-Mar-16-2026_23-57-28   category: movies
02:13:07  INFO      ── Step 1: Loading base model ──────────────────
02:13:10  INFO      NumExpr defaulting to 2 threads.
2026-03-18 02:13:14.039064: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-18 02:13:14.494219: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-18 02:13:14.700267: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1773799994.759846   22562 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1773799994.773374   22562 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1773799994.820615   22562 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773799994.820689   22562 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773799994.820695   22562 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1773799994.820700   22562 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-03-18 02:13:14.826775: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
02:13:31  INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv1/RecBole/recbole/config/../dataset_example/ml-100k
checkpoint_dir = saved
show_progress = True
save_dataset = False
dataset_save_path = None
save_dataloaders = False
dataloaders_save_path = None
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 20
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10, 20, 50]
valid_metric = MRR@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = None
item_inter_num_interval = None
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = True
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
kg_reverse_r = False
entity_kg_num_interval = None
relation_kg_num_interval = None
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 3
reg_weight = 0.0001
numerical_features = []
discretization = None
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cpu
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
02:13:31  INFO      ml-100k
The number of users: 944
Average actions of users: 106.04453870625663
The number of items: 1683
Average actions of items: 59.45303210463734
The number of inters: 100000
The sparsity of the dataset: 93.70575143257098%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp']
02:13:32  INFO      [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
02:13:32  INFO      [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'RO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/content/drive/MyDrive/Colab_Notebooks/CIKMv2/RecBole/recbole/model/general_recommender/lightgcn.py:126: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:654.)
  SparseL = torch.sparse.FloatTensor(i, data, torch.Size(L.shape))
02:13:33  INFO      Model=LightGCN uses=944 items=1683  dim=64
02:13:33  INFO      Item side-info loaded for 1682 items  (fields: ['movie_title', 'release_year', 'class'])
02:13:33  INFO      Object saved to ./results/item_side_info.json
02:13:33  INFO      ── Step 2: Loading SAE from saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth ──
02:13:33  INFO      Loaded SAE from saved/LightGCN-Mar-16-2026_23-57-28-SAE_ver_user.pth  (input=64, latent=1024, k=8)
02:13:33  INFO      SAE latent_dim=1024  k=8
02:13:33  INFO      ── Step 3: Encoding item embeddings through SAE ─
02:13:33  INFO      item_acts shape=(1683, 1024)  non-zero=0.8%
02:13:33  INFO      ── Step 4: Ranking top items per neuron ────────
02:13:33  INFO      Active neurons (≥1 item): 49/1024  (dead: 975)
02:13:33  INFO      ── Step 5: LLM neuron labelling ────────────────
02:13:39  INFO      Loading HF model: HuggingFaceTB/SmolLM2-1.7B-Instruct
02:13:39  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
02:13:39  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/config.json "HTTP/1.1 200 OK"
02:13:39  INFO      HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/config.json "HTTP/1.1 200 OK"
config.json: 100% 908/908 [00:00<00:00, 2.74MB/s]
02:13:40  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
`torch_dtype` is deprecated! Use `dtype` instead!
02:13:40  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
02:13:40  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/config.json "HTTP/1.1 200 OK"
02:13:40  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/model.safetensors "HTTP/1.1 302 Found"
02:13:40  INFO      HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/xet-read-token/31b70e2e869a7173562077fd711b654946d38674 "HTTP/1.1 200 OK"
model.safetensors: 100% 3.42G/3.42G [00:49<00:00, 68.5MB/s]
Loading weights: 100% 218/218 [00:00<00:00, 383.46it/s, Materializing param=model.norm.weight]
02:14:31  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
02:14:31  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/generation_config.json "HTTP/1.1 200 OK"
02:14:31  INFO      HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/generation_config.json "HTTP/1.1 200 OK"
generation_config.json: 100% 132/132 [00:00<00:00, 408kB/s]
02:14:31  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
02:14:31  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/tokenizer_config.json "HTTP/1.1 200 OK"
02:14:31  INFO      HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/tokenizer_config.json "HTTP/1.1 200 OK"
tokenizer_config.json: 3.76kB [00:00, 487kB/s]
02:14:32  INFO      HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
02:14:32  INFO      HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/tokenizer.json "HTTP/1.1 200 OK"
02:14:32  INFO      HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/tokenizer.json "HTTP/1.1 200 OK"
tokenizer.json: 2.10MB [00:00, 13.9MB/s]
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/tokenizer.model "HTTP/1.1 404 Not Found"
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/added_tokens.json "HTTP/1.1 404 Not Found"
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
02:14:32  INFO      HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/special_tokens_map.json "HTTP/1.1 200 OK"
02:14:32  INFO      HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-1.7B-Instruct/31b70e2e869a7173562077fd711b654946d38674/special_tokens_map.json "HTTP/1.1 200 OK"
special_tokens_map.json: 100% 655/655 [00:00<00:00, 3.60MB/s]
02:14:33  INFO      HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct/resolve/main/chat_template.jinja "HTTP/1.1 404 Not Found"
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
02:17:49  INFO        [1/49] neuron    1 → "Classic, Romantic, Comedies"
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=32) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

### Step 2: Choose a method to persist the cache

#### Method A: Set `HF_HOME` environment variable
This is often the cleanest way, as many libraries (like Hugging Face Transformers) respect this variable to determine where to store models and datasets.

In [19]:
import os

# Define your cache directory in Google Drive
cache_dir = '/content/drive/MyDrive/huggingface_cache'

# Create the directory if it doesn't exist
os.makedirs(cache_dir, exist_ok=True)

# Set the HF_HOME environment variable
os.environ['HF_HOME'] = cache_dir

print(f"Hugging Face cache directory set to: {os.environ['HF_HOME']}")
print("Models will now be downloaded to and loaded from this location.")

Hugging Face cache directory set to: /content/drive/MyDrive/huggingface_cache
Models will now be downloaded to and loaded from this location.

#### Method B: Create a symbolic link
This method redirects the default cache location (`~/.cache/huggingface/transformers`) to a directory in your Google Drive. This is useful if a library doesn't respect `HF_HOME` or you prefer to use the default paths.

In [ ]:
import os

# Define your cache directory in Google Drive
drive_cache_path = '/content/drive/MyDrive/huggingface_cache_symlink'

# Define the default cache path
default_cache_path = os.path.expanduser('~/.cache/huggingface')

# Create the directory in Drive if it doesn't exist
os.makedirs(drive_cache_path, exist_ok=True)

# Remove the existing default cache directory if it's not a symlink
if os.path.exists(default_cache_path) and not os.path.islink(default_cache_path):
    # You might want to move existing files first if you have any
    # import shutil
    # shutil.move(default_cache_path, drive_cache_path)
    !rm -rf {default_cache_path}

# Create a symbolic link if it doesn't exist
if not os.path.islink(default_cache_path):
    # Create the parent directory for the symlink target if it doesn't exist
    os.makedirs(os.path.dirname(default_cache_path), exist_ok=True)
    !ln -s {drive_cache_path} {default_cache_path}
    print(f"Symbolic link created: {default_cache_path} -> {drive_cache_path}")
else:
    print(f"Symbolic link already exists for {default_cache_path}.")

print("Models will now be downloaded to and loaded from the symlinked location in Google Drive.")

After running one of these methods, when you download an LLM using libraries like Hugging Face Transformers, it will be stored in the specified location within your Google Drive. On subsequent Colab sessions (after re-mounting Drive and running the cache persistence code), the models will be loaded directly from Drive, saving download time.

# Trial 3:

## preprocess dataset/Grocery_and_Gourmet_Food

In [6]:
RAW_REVIEWS = "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/Grocery_and_Gourmet_Food/Grocery_and_Gourmet_Food_5.json.gz"
RAW_META    = "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/Grocery_and_Gourmet_Food/meta_Grocery_and_Gourmet_Food.json.gz"
OUT_DIR     = "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery"
DATASET_NAME = "amazon-grocery"
MIN_INTERACTIONS = 5

In [ ]:
import gzip
import json
import os
import re
import pandas as pd
from collections import defaultdict

def load_gzip_json(path: str):
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue

def clean_text(text) -> str:
    if not text:
        return "unknown"
    if isinstance(text, list):
        text = " ".join(str(t) for t in text)
    text = re.sub(r"\t|\n|\r", " ", str(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text

def apply_kcore(df: pd.DataFrame, k: int = 5) -> pd.DataFrame:
    while True:
        user_counts = df.groupby("user_id").size()
        item_counts = df.groupby("item_id").size()
        prev_len = len(df)
        df = df[
            df["user_id"].isin(user_counts[user_counts >= k].index) &
            df["item_id"].isin(item_counts[item_counts >= k].index)
        ]
        if len(df) == prev_len:
            break
    return df.reset_index(drop=True)

def preprocess():
    os.makedirs(OUT_DIR, exist_ok=True)

    # ── Load item metadata (all fields) ───────────────────────────────────
    print("Loading item metadata...")
    meta = {}
    all_meta_keys = set()

    for item in load_gzip_json(RAW_META):
        asin = item.get("asin", "")
        if not asin: continue

        # Store everything except asin
        item_data = {k: clean_text(v) for k, v in item.items() if k != "asin"}
        meta[asin] = item_data
        all_meta_keys.update(item_data.keys())

    # ── Load interactions ──────────────────────────────────────────────────
    print("Loading reviews...")
    rows = []
    for r in load_gzip_json(RAW_REVIEWS):
        uid = r.get("reviewerID", "")
        iid = r.get("asin", "")
        ts = float(r.get("unixReviewTime", 0))
        if uid and iid:
            rows.append((uid, iid, ts))

    df = pd.DataFrame(rows, columns=["user_id", "item_id", "timestamp"])
    df.drop_duplicates(subset=["user_id", "item_id"], keep="last", inplace=True)

    print("Applying 5-core filter...")
    df = apply_kcore(df, k=MIN_INTERACTIONS)

    # ── Write .inter ────────────────────────────────────────────────────────
    inter_path = os.path.join(OUT_DIR, f"{DATASET_NAME}.inter")
    df.to_csv(inter_path, sep="\t", index=False, header=["user_id:token", "item_id:token", "timestamp:float"])
    print(f"Saved {inter_path}")

    # ── Write .item ─────────────────────────────────────────────────────────
    item_path = os.path.join(OUT_DIR, f"{DATASET_NAME}.item")
    all_items = df["item_id"].unique()

    # Prepare header: item_id + all other fields detected as token_seq
    sorted_keys = sorted(list(all_meta_keys))
    header = ["item_id:token"] + [f"{k}:token_seq" for k in sorted_keys]

    with open(item_path, "w", encoding="utf-8") as f:
        f.write("\t".join(header) + "\n")
        for iid in all_items:
            row = [iid]
            item_meta = meta.get(iid, {})
            for k in sorted_keys:
                row.append(item_meta.get(k, "unknown"))
            f.write("\t".join(row) + "\n")

    print(f"Saved {item_path}")
    print(f"Stats: {df['user_id'].nunique()} users | {len(all_items)} items | {len(df)} interactions")

In [ ]:
preprocess()

Loading item metadata...
Loading reviews...
Applying 5-core filter...
Saved /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery.inter
Saved /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery.item
Stats: 113592 users | 39504 items | 1005817 interactions

In [7]:
import pandas as pd
import os

# Paths to the generated files
inter_file = os.path.join(OUT_DIR, f'{DATASET_NAME}.inter')
item_file = os.path.join(OUT_DIR, f'{DATASET_NAME}.item')

print('--- Inspecting .inter file (first 5 lines) ---')
with open(inter_file, 'r') as f:
    for i in range(5):
        print(f.readline().strip())

print('\n--- Inspecting .item file (first 2 lines to see columns and one entry) ---')
with open(item_file, 'r') as f:
    for i in range(2):
        print(f.readline().strip())

# Also load a few rows with pandas to show the structure clearly
print('\n--- Data Preview ---')
item_df_preview = pd.read_csv(item_file, sep='\t', nrows=5)
display(item_df_preview)

--- Inspecting .inter file (first 5 lines) ---
user_id:token	item_id:token	timestamp:float
A1QVBUH9E1V6I8	4639725183	1416355200.0
A3GEOILWLK86XM	4639725183	1476316800.0
A32RD6L701BIGP	4639725183	1448064000.0
A2UY1O1FBGKIE6	4639725183	1439337600.0

--- Inspecting .item file (first 2 lines to see columns and one entry) ---
item_id:token	also_buy:token_seq	also_view:token_seq	brand:token_seq	category:token_seq	date:token_seq	description:token_seq	details:token_seq	feature:token_seq	fit:token_seq	imageURL:token_seq	imageURLHighRes:token_seq	main_cat:token_seq	price:token_seq	rank:token_seq	similar_item:token_seq	tech1:token_seq	tech2:token_seq	title:token_seq
4639725183	B000JSQDK4 B007ZI1SKG 4639725043 B00KPFHOPO B01LY2304D B00GRS0CAM B00RZ7EOC6 B007SH2C6S B000MQ5YRQ B00286KM8E B0005XMOI8 B000GG5IYQ B009UQXD90 B00BOMGIBI	B000JSQDK4 B007ZI1SKG B00286KM8E B01LY2304D 4639725043 B00BOMGIBI B00CISKNPO B00U9W37QS B003CJJLYW B00KO3O1BC B002YJC990 B003CJLNT8 B000MQ5YRQ B007ZI1UFY B003D4MYLS B000MXVHCA B00CREXSHY B00YPICDXK B00RZ7EOC6 B00UZNYKTE B002EYZM4O B00CREY86Y B00KV586SC B0005XMOI8 B001GM60LE B0042IMPTU B01IMWBCFY B001XUFDJ4 B0160988SU B0062JSYEW	Lipton	Grocery & Gourmet Food Beverages Coffee, Tea & Cocoa Tea Black	unknown	Lipton Yellow Label Teabags uses a new way to make tea. To lock in as much of the tea taste and aroma as possible, we developed an innovative new process. We press fresh, high quality tea leaves to release their natural essence and we have developed a new blend with this essence. Enjoy a cup of tea with perfect color and taste that reinvigorates you. Shipping weight 14.00 Keywords Search Terms black tea bags Lipton tea bags Statements regarding dietary supplements have not been evaluated by the FDA and are not intended to diagnose, treat, cure, or prevent any disease or health condition.	unknown	unknown	unknown	https://images-na.ssl-images-amazon.com/images/I/31TlgFpkgZL._SS40_.jpg	https://images-na.ssl-images-amazon.com/images/I/31TlgFpkgZL.jpg	Grocery	$12.98	15,487 in Grocery & Gourmet Food (	unknown	unknown	unknown	Lipton Yellow Label Finest Blend Tea Bags 100 tea bags Pack of 2 (2 x 7 ox / 2 x 200 g)

--- Data Preview ---

,item_id:token,also_buy:token_seq,also_view:token_seq,brand:token_seq,category:token_seq,date:token_seq,description:token_seq,details:token_seq,feature:token_seq,fit:token_seq,imageURL:token_seq,imageURLHighRes:token_seq,main_cat:token_seq,price:token_seq,rank:token_seq,similar_item:token_seq,tech1:token_seq,tech2:token_seq,title:token_seq
0,4639725183,B000JSQDK4 B007ZI1SKG 4639725043 B00KPFHOPO B0...,B000JSQDK4 B007ZI1SKG B00286KM8E B01LY2304D 46...,Lipton,"Grocery & Gourmet Food Beverages Coffee, Tea &...",unknown,Lipton Yellow Label Teabags uses a new way to ...,unknown,unknown,unknown,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,Grocery,$12.98,"15,487 in Grocery & Gourmet Food (",unknown,unknown,unknown,Lipton Yellow Label Finest Blend Tea Bags 100 ...
1,4639725043,B00886E4K0 B00CREXSHY B001QTRGAQ B002EYZM4O B0...,B00CREXSHY B001QTRGAQ B000JSQK70 B002EYZM4O B0...,Lipton,"Grocery & Gourmet Food Beverages Coffee, Tea &...",unknown,Lipton Yellow Label Tea use only the finest te...,unknown,unknown,unknown,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,Grocery,$12.46,"30,937 in Grocery & Gourmet Food (",unknown,unknown,unknown,Lipton Yellow Label Tea (loose tea) - 450g
2,5463213682,B00F3XJX6G B003CY45VG B003CGJAIM B00E1C3FJG B0...,B003CGJAIM B00F3XJX6G B01LVXI1GP B00E1C3FJG B0...,Organo Gold,"Grocery & Gourmet Food Beverages Coffee, Tea &...",unknown,20 Sachets Empty contents into cup Pour 8oz of...,unknown,unknown,unknown,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,Grocery,$29.90,"89,943 in Grocery & Gourmet Food (",unknown,unknown,unknown,Organo Gold Cafe Supreme 100% Certified Ganode...
3,9742356831,B000EICJWA B000EICISA B074ZMGQNT B0044PYPVC B0...,B002P8AQJ0 B000EICISA B0091UW4QS B006VD15F4 B0...,Mae Ploy,"Grocery & Gourmet Food Sauces, Gravies & Marin...",unknown,Mae Ploy Thai green curry paste. Ingredients g...,{'\n Product Dimensions: \n ': '3.6 x 3.6 x 3....,unknown,unknown,https://images-na.ssl-images-amazon.com/images...,https://images-na.ssl-images-amazon.com/images...,Grocery,unknown,"39,261 in Grocery & Gourmet Food (",unknown,unknown,unknown,"Mae Ploy Green Curry Paste, 14 oz"
4,B00004S1C5,unknown,B00KCUXRLC B0026N2Y3U B01BZ5U3Y6 B01DWEZB5E B0...,Harold Import Company,Grocery & Gourmet Food Cooking & Baking Food C...,"June 6, 2006",This set is a great value from one of the grea...,unknown,"Six certified gel colors included - black, blu...",unknown,unknown,unknown,Amazon Home,unknown,">#257,139 in Kitchen & Dining (See Top 100 in ...",unknown,unknown,unknown,"Ateco Food Coloring Kit, 6 colors"

In [ ]:
# Re-load the full item dataset to check for missing values
item_df = pd.read_csv(item_file, sep='\t')

print("--- Missing Value Analysis ---")
# 1. Check for actual Null/NaN values
nan_counts = item_df.isna().sum()

# 2. Check for our 'unknown' placeholder
unknown_counts = (item_df == 'unknown').sum()

missing_report = pd.DataFrame({
    'NaN Count': nan_counts,
    '\'unknown\' Count': unknown_counts,
    'Total Missing/Unknown': nan_counts + unknown_counts
})

display(missing_report.sort_values(by='Total Missing/Unknown', ascending=False))

--- Missing Value Analysis ---

                           NaN Count  'unknown' Count  Total Missing/Unknown
tech2:token_seq                    5            39414                  39419
fit:token_seq                      1            39414                  39415
similar_item:token_seq             1            39366                  39367
tech1:token_seq                    1            39329                  39330
date:token_seq                     0            38903                  38903
feature:token_seq                  1            35974                  35975
also_view:token_seq                0            18328                  18328
price:token_seq                    1            14911                  14912
also_buy:token_seq                 0            10980                  10980
imageURLHighRes:token_seq          1             7608                   7609
imageURL:token_seq                 1             7606                   7607
description:token_seq              0             3277                   3277
rank:token_seq                     1             2376                   2377
details:token_seq                  1              968                    969
brand:token_seq                    0              426                    426
main_cat:token_seq                 1               85                     86
title:token_seq                    5               30                     35
category:token_seq                 0               30                     30
item_id:token                      0                0                      0

In [8]:
import pandas as pd
import os

# Paths to the generated files are already in kernel state
# item_file = os.path.join(OUT_DIR, f'{DATASET_NAME}.item')
# inter_file = os.path.join(OUT_DIR, f'{DATASET_NAME}.inter')

# Load the item and interaction data
item_df = pd.read_csv(item_file, sep='\t')
inter_df = pd.read_csv(inter_file, sep='\t')

In [9]:
print('Original item_df columns:', item_df.columns.tolist())

# Select the specified columns from item_df
selected_columns = [
    'item_id:token',
    'category:token_seq',
    'title:token_seq',
    'main_cat:token_seq',
    'brand:token_seq',
    'details:token_seq',
    'rank:token_seq',
    'description:token_seq',
    'price:token_seq'
]

# Filter for existence to avoid errors if a column doesn't exist
existing_columns = [col for col in selected_columns if col in item_df.columns]
item_df_processed = item_df[existing_columns].copy()

# Rename columns for clarity, removing ':token' or ':token_seq' suffix
item_df_processed.columns = [col.split(':')[0] for col in item_df_processed.columns]

display(item_df_processed.head())

Original item_df columns: ['item_id:token', 'also_buy:token_seq', 'also_view:token_seq', 'brand:token_seq', 'category:token_seq', 'date:token_seq', 'description:token_seq', 'details:token_seq', 'feature:token_seq', 'fit:token_seq', 'imageURL:token_seq', 'imageURLHighRes:token_seq', 'main_cat:token_seq', 'price:token_seq', 'rank:token_seq', 'similar_item:token_seq', 'tech1:token_seq', 'tech2:token_seq', 'title:token_seq']

,item_id,category,title,main_cat,brand,details,rank,description,price
0,4639725183,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Finest Blend Tea Bags 100 ...,Grocery,Lipton,unknown,"15,487 in Grocery & Gourmet Food (",Lipton Yellow Label Teabags uses a new way to ...,$12.98
1,4639725043,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Tea (loose tea) - 450g,Grocery,Lipton,unknown,"30,937 in Grocery & Gourmet Food (",Lipton Yellow Label Tea use only the finest te...,$12.46
2,5463213682,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Organo Gold Cafe Supreme 100% Certified Ganode...,Grocery,Organo Gold,unknown,"89,943 in Grocery & Gourmet Food (",20 Sachets Empty contents into cup Pour 8oz of...,$29.90
3,9742356831,"Grocery & Gourmet Food Sauces, Gravies & Marin...","Mae Ploy Green Curry Paste, 14 oz",Grocery,Mae Ploy,{'\n Product Dimensions: \n ': '3.6 x 3.6 x 3....,"39,261 in Grocery & Gourmet Food (",Mae Ploy Thai green curry paste. Ingredients g...,unknown
4,B00004S1C5,Grocery & Gourmet Food Cooking & Baking Food C...,"Ateco Food Coloring Kit, 6 colors",Amazon Home,Harold Import Company,unknown,">#257,139 in Kitchen & Dining (See Top 100 in ...",This set is a great value from one of the grea...,unknown

In [10]:
# Calculate item popularity from inter_df
# Count interactions for each item
item_popularity = inter_df.groupby('item_id:token').size().reset_index(name='interaction_count')

# Rank items by interaction count (higher count = more popular = lower rank number)
item_popularity['popularity_rank'] = item_popularity['interaction_count'].rank(ascending=False).astype(int)

# Rename item_id column for merging
item_popularity.rename(columns={'item_id:token': 'item_id'}, inplace=True)

display(item_popularity.head())

      item_id  interaction_count  popularity_rank
0  4639725043                 29             7134
1  4639725183                 12            17241
2  5463213682                  8            24779
3  9742356831                 94             1682
4  B00004S1C5                 14            14987

In [11]:
# Merge popularity data with the processed item_df
final_item_df = pd.merge(
    item_df_processed,
    item_popularity[['item_id', 'interaction_count', 'popularity_rank']],
    on='item_id',
    how='left'
)

# Fill any potential NaN values for popularity if items in item_df_processed were not in inter_df
final_item_df['interaction_count'].fillna(0, inplace=True)
final_item_df['popularity_rank'].fillna(len(item_popularity) + 1, inplace=True) # Assign a low rank if no interactions

print("Final DataFrame with selected fields and popularity rank:")
display(final_item_df.head())
print(f"Shape of the final DataFrame: {final_item_df.shape}")

Final DataFrame with selected fields and popularity rank:

/tmp/ipykernel_15663/2133966362.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_item_df['interaction_count'].fillna(0, inplace=True)
/tmp/ipykernel_15663/2133966362.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_item_df['popularity_rank'].fillna(len(item_popularity) + 1, inplace=True) # Assign a low rank if no interactions

,item_id,category,title,main_cat,brand,details,rank,description,price,interaction_count,popularity_rank
0,4639725183,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Finest Blend Tea Bags 100 ...,Grocery,Lipton,unknown,"15,487 in Grocery & Gourmet Food (",Lipton Yellow Label Teabags uses a new way to ...,$12.98,12,17241
1,4639725043,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Tea (loose tea) - 450g,Grocery,Lipton,unknown,"30,937 in Grocery & Gourmet Food (",Lipton Yellow Label Tea use only the finest te...,$12.46,29,7134
2,5463213682,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Organo Gold Cafe Supreme 100% Certified Ganode...,Grocery,Organo Gold,unknown,"89,943 in Grocery & Gourmet Food (",20 Sachets Empty contents into cup Pour 8oz of...,$29.90,8,24779
3,9742356831,"Grocery & Gourmet Food Sauces, Gravies & Marin...","Mae Ploy Green Curry Paste, 14 oz",Grocery,Mae Ploy,{'\n Product Dimensions: \n ': '3.6 x 3.6 x 3....,"39,261 in Grocery & Gourmet Food (",Mae Ploy Thai green curry paste. Ingredients g...,unknown,94,1682
4,B00004S1C5,Grocery & Gourmet Food Cooking & Baking Food C...,"Ateco Food Coloring Kit, 6 colors",Amazon Home,Harold Import Company,unknown,">#257,139 in Kitchen & Dining (See Top 100 in ...",This set is a great value from one of the grea...,unknown,14,14987

Shape of the final DataFrame: (39419, 11)

In [12]:
import os

# Define the mapping of column names to RecBole types
# item_id is usually a token, others here are sequences or tokens
# We'll use :token for ID and :token_seq for descriptive fields to maintain consistency with the original format
column_mapping = {
    'item_id': 'item_id:token',
    'category': 'category:token_seq',
    'title': 'title:token_seq',
    'main_cat': 'main_cat:token_seq',
    'brand': 'brand:token_seq',
    'details': 'details:token_seq',
    'rank': 'rank:token_seq',
    'description': 'description:token_seq',
    'price': 'price:token_seq',
    'interaction_count': 'interaction_count:float',
    'popularity_rank': 'popularity_rank:float'
}

# Create a copy for export
export_df = final_item_df.copy()

# Rename columns
export_df.rename(columns=column_mapping, inplace=True)

# Define output path (overwriting the original or creating a new one)
output_item_path = os.path.join(OUT_DIR, f'{DATASET_NAME}.item')

# Save as tab-separated file
export_df.to_csv(output_item_path, sep='\t', index=False)

print(f"Successfully saved processed metadata to: {output_item_path}")
display(export_df.head())

Successfully saved processed metadata to: /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery.item

,item_id:token,category:token_seq,title:token_seq,main_cat:token_seq,brand:token_seq,details:token_seq,rank:token_seq,description:token_seq,price:token_seq,interaction_count:float,popularity_rank:float
0,4639725183,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Finest Blend Tea Bags 100 ...,Grocery,Lipton,unknown,"15,487 in Grocery & Gourmet Food (",Lipton Yellow Label Teabags uses a new way to ...,$12.98,12,17241
1,4639725043,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Lipton Yellow Label Tea (loose tea) - 450g,Grocery,Lipton,unknown,"30,937 in Grocery & Gourmet Food (",Lipton Yellow Label Tea use only the finest te...,$12.46,29,7134
2,5463213682,"Grocery & Gourmet Food Beverages Coffee, Tea &...",Organo Gold Cafe Supreme 100% Certified Ganode...,Grocery,Organo Gold,unknown,"89,943 in Grocery & Gourmet Food (",20 Sachets Empty contents into cup Pour 8oz of...,$29.90,8,24779
3,9742356831,"Grocery & Gourmet Food Sauces, Gravies & Marin...","Mae Ploy Green Curry Paste, 14 oz",Grocery,Mae Ploy,{'\n Product Dimensions: \n ': '3.6 x 3.6 x 3....,"39,261 in Grocery & Gourmet Food (",Mae Ploy Thai green curry paste. Ingredients g...,unknown,94,1682
4,B00004S1C5,Grocery & Gourmet Food Cooking & Baking Food C...,"Ateco Food Coloring Kit, 6 colors",Amazon Home,Harold Import Company,unknown,">#257,139 in Kitchen & Dining (See Top 100 in ...",This set is a great value from one of the grea...,unknown,14,14987

## Train LightGCN on Amazon Food

In [14]:
!pip install "numpy<2.0.0"

Collecting numpy<2.0.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 7.1 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 95.8 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [4]:
cd RecBole-SAE/

/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE

In [5]:
!python ../RecBole/run_recbole.py \
    --model LightGCN \
    --dataset amazon-grocery \
    --config_files configs/LightGCN/amazon-grocery.yaml \
    --data_path="/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/" \
    --load_col="{'inter': ['user_id', 'item_id', 'timestamp']}"

2026-04-08 23:20:21.241880: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775690421.262821   16220 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775690421.269730   16220 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775690421.288352   16220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775690421.288375   16220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775690421.288379   16220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775690421.288388   16220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-04-08 23:20:21.293680: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
command line args [--model LightGCN --dataset amazon-grocery --config_files configs/LightGCN/amazon-grocery.yaml] will not be used in RecBole
08 Apr 23:22    INFO  ['../RecBole/run_recbole.py', '--model', 'LightGCN', '--dataset', 'amazon-grocery', '--config_files', 'configs/LightGCN/amazon-grocery.yaml', '--data_path=/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/', "--load_col={'inter': ['user_id', 'item_id', 'timestamp']}"]
08 Apr 23:22    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery
checkpoint_dir = saved
show_progress = True
save_dataset = True
dataset_save_path = saved_data/
save_dataloaders = True
dataloaders_save_path = saved_dataloader/
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 30
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 2
reg_weight = 0.0001
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
08 Apr 23:22    INFO  Saving filtered dataset into [saved/amazon-grocery-Dataset.pth]
08 Apr 23:22    INFO  amazon-grocery
The number of users: 113593
Average actions of users: 8.854646453975633
The number of items: 39505
Average actions of items: 25.461143175374644
The number of inters: 1005817
The sparsity of the dataset: 99.97758620806647%
Remain Fields: ['user_id', 'item_id', 'timestamp']
08 Apr 23:22    INFO  Saving split dataloaders into: [saved/amazon-grocery-for-LightGCN-dataloader.pth]
08 Apr 23:23    INFO  [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
08 Apr 23:23    INFO  [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/model/general_recommender/lightgcn.py:126: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:654.)
  SparseL = torch.sparse.FloatTensor(i, data, torch.Size(L.shape))
08 Apr 23:24    INFO  LightGCN(
  (user_embedding): Embedding(113593, 64)
  (item_embedding): Embedding(39505, 64)
  (mf_loss): BPRLoss()
  (reg_loss): EmbLoss()
)
Trainable parameters: 9798272
08 Apr 23:24    INFO  FLOPs: 0.0
Train     0:   0%|                                                          | 0/185 [00:00<?, ?it/s]/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/trainer/trainer.py:235: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = amp.GradScaler(enabled=self.enable_scaler)
Train     0: 100%|███████████████████████| 185/185 [00:15<00:00, 12.33it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:24    INFO  epoch 0 training [time: 15.00s, train loss: 110.6125]
Train     1: 100%|███████████████████████| 185/185 [00:14<00:00, 12.81it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:24    INFO  epoch 1 training [time: 14.45s, train loss: 77.6032]
Train     2: 100%|███████████████████████| 185/185 [00:14<00:00, 12.72it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:25    INFO  epoch 2 training [time: 14.54s, train loss: 70.3992]
Train     3: 100%|███████████████████████| 185/185 [00:14<00:00, 12.63it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:25    INFO  epoch 3 training [time: 14.65s, train loss: 67.3078]
Train     4: 100%|███████████████████████| 185/185 [00:14<00:00, 12.46it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:25    INFO  epoch 4 training [time: 14.85s, train loss: 64.8084]
Train     5: 100%|███████████████████████| 185/185 [00:15<00:00, 12.29it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:25    INFO  epoch 5 training [time: 15.05s, train loss: 62.2222]
Train     6: 100%|███████████████████████| 185/185 [00:15<00:00, 12.13it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:26    INFO  epoch 6 training [time: 15.25s, train loss: 59.7937]
Train     7: 100%|███████████████████████| 185/185 [00:15<00:00, 12.05it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:26    INFO  epoch 7 training [time: 15.35s, train loss: 57.3051]
Train     8: 100%|███████████████████████| 185/185 [00:15<00:00, 12.23it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:26    INFO  epoch 8 training [time: 15.12s, train loss: 55.1568]
Train     9: 100%|███████████████████████| 185/185 [00:15<00:00, 12.30it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:26    INFO  epoch 9 training [time: 15.04s, train loss: 52.9974]
Evaluate   : 100%|████████████████| 113592/113592 [02:46<00:00, 680.50it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:29    INFO  epoch 9 evaluating [time: 167.46s, valid_score: 0.035700]
08 Apr 23:29    INFO  valid result:
recall@10 : 0.0517    mrr@10 : 0.031    ndcg@10 : 0.0357    hit@10 : 0.0529    precision@10 : 0.0053
08 Apr 23:29    INFO  Saving current: saved/LightGCN-Apr-08-2026_23-24-12.pth
Train    10: 100%|███████████████████████| 185/185 [00:15<00:00, 11.79it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:29    INFO  epoch 10 training [time: 15.69s, train loss: 50.9778]
Train    11: 100%|███████████████████████| 185/185 [00:15<00:00, 11.96it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:30    INFO  epoch 11 training [time: 15.47s, train loss: 49.0133]
Train    12: 100%|███████████████████████| 185/185 [00:15<00:00, 12.22it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:30    INFO  epoch 12 training [time: 15.14s, train loss: 47.2609]
Train    13: 100%|███████████████████████| 185/185 [00:15<00:00, 12.29it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:30    INFO  epoch 13 training [time: 15.05s, train loss: 45.4521]
Train    14: 100%|███████████████████████| 185/185 [00:15<00:00, 12.31it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:30    INFO  epoch 14 training [time: 15.04s, train loss: 43.9397]
Train    15: 100%|███████████████████████| 185/185 [00:15<00:00, 12.29it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:31    INFO  epoch 15 training [time: 15.06s, train loss: 42.4024]
Train    16: 100%|███████████████████████| 185/185 [00:15<00:00, 12.06it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:31    INFO  epoch 16 training [time: 15.34s, train loss: 40.6891]
Train    17: 100%|███████████████████████| 185/185 [00:15<00:00, 12.09it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:31    INFO  epoch 17 training [time: 15.30s, train loss: 39.1557]
Train    18: 100%|███████████████████████| 185/185 [00:15<00:00, 12.12it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:31    INFO  epoch 18 training [time: 15.27s, train loss: 37.6296]
Train    19: 100%|███████████████████████| 185/185 [00:15<00:00, 12.18it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:32    INFO  epoch 19 training [time: 15.19s, train loss: 36.1517]
Evaluate   : 100%|████████████████| 113592/113592 [02:44<00:00, 688.81it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:34    INFO  epoch 19 evaluating [time: 165.38s, valid_score: 0.043000]
08 Apr 23:34    INFO  valid result:
recall@10 : 0.0609    mrr@10 : 0.0379    ndcg@10 : 0.043    hit@10 : 0.0628    precision@10 : 0.0063
08 Apr 23:34    INFO  Saving current: saved/LightGCN-Apr-08-2026_23-24-12.pth
Train    20: 100%|███████████████████████| 185/185 [00:15<00:00, 11.76it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:35    INFO  epoch 20 training [time: 15.73s, train loss: 34.6828]
Train    21: 100%|███████████████████████| 185/185 [00:15<00:00, 11.75it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:35    INFO  epoch 21 training [time: 15.75s, train loss: 33.2989]
Train    22: 100%|███████████████████████| 185/185 [00:15<00:00, 12.15it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:35    INFO  epoch 22 training [time: 15.22s, train loss: 31.7918]
Train    23: 100%|███████████████████████| 185/185 [00:15<00:00, 12.22it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:35    INFO  epoch 23 training [time: 15.14s, train loss: 30.4881]
Train    24: 100%|███████████████████████| 185/185 [00:15<00:00, 12.22it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:36    INFO  epoch 24 training [time: 15.14s, train loss: 29.1876]
Train    25: 100%|███████████████████████| 185/185 [00:15<00:00, 12.24it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:36    INFO  epoch 25 training [time: 15.12s, train loss: 27.8297]
Train    26: 100%|███████████████████████| 185/185 [00:15<00:00, 12.19it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:36    INFO  epoch 26 training [time: 15.18s, train loss: 26.6811]
Train    27: 100%|███████████████████████| 185/185 [00:15<00:00, 12.20it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:36    INFO  epoch 27 training [time: 15.17s, train loss: 25.3851]
Train    28: 100%|███████████████████████| 185/185 [00:15<00:00, 12.26it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:37    INFO  epoch 28 training [time: 15.09s, train loss: 24.2519]
Train    29: 100%|███████████████████████| 185/185 [00:15<00:00, 12.30it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:37    INFO  epoch 29 training [time: 15.04s, train loss: 23.1056]
Evaluate   : 100%|████████████████| 113592/113592 [02:47<00:00, 677.11it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:40    INFO  epoch 29 evaluating [time: 168.29s, valid_score: 0.045800]
08 Apr 23:40    INFO  valid result:
recall@10 : 0.0664    mrr@10 : 0.04    ndcg@10 : 0.0458    hit@10 : 0.0686    precision@10 : 0.0069
08 Apr 23:40    INFO  Saving current: saved/LightGCN-Apr-08-2026_23-24-12.pth
Train    30: 100%|███████████████████████| 185/185 [00:16<00:00, 11.22it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:40    INFO  epoch 30 training [time: 16.48s, train loss: 22.1604]
Train    31: 100%|███████████████████████| 185/185 [00:15<00:00, 11.96it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:40    INFO  epoch 31 training [time: 15.47s, train loss: 21.0150]
Train    32: 100%|███████████████████████| 185/185 [00:15<00:00, 12.23it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:41    INFO  epoch 32 training [time: 15.12s, train loss: 20.0574]
Train    33: 100%|███████████████████████| 185/185 [00:15<00:00, 12.32it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:41    INFO  epoch 33 training [time: 15.01s, train loss: 19.1668]
Train    34: 100%|███████████████████████| 185/185 [00:15<00:00, 12.32it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:41    INFO  epoch 34 training [time: 15.02s, train loss: 18.0722]
Train    35: 100%|███████████████████████| 185/185 [00:15<00:00, 12.29it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:41    INFO  epoch 35 training [time: 15.06s, train loss: 17.4188]
Train    36: 100%|███████████████████████| 185/185 [00:15<00:00, 12.24it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:42    INFO  epoch 36 training [time: 15.11s, train loss: 16.6177]
Train    37: 100%|███████████████████████| 185/185 [00:15<00:00, 12.23it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:42    INFO  epoch 37 training [time: 15.12s, train loss: 15.9438]
Train    38: 100%|███████████████████████| 185/185 [00:15<00:00, 12.26it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:42    INFO  epoch 38 training [time: 15.09s, train loss: 15.2124]
Train    39: 100%|███████████████████████| 185/185 [00:15<00:00, 12.28it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:42    INFO  epoch 39 training [time: 15.07s, train loss: 14.5111]
Evaluate   : 100%|████████████████| 113592/113592 [02:44<00:00, 688.45it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:45    INFO  epoch 39 evaluating [time: 165.46s, valid_score: 0.049200]
08 Apr 23:45    INFO  valid result:
recall@10 : 0.0724    mrr@10 : 0.0427    ndcg@10 : 0.0492    hit@10 : 0.0747    precision@10 : 0.0075
08 Apr 23:45    INFO  Saving current: saved/LightGCN-Apr-08-2026_23-24-12.pth
Train    40: 100%|███████████████████████| 185/185 [00:15<00:00, 11.61it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:45    INFO  epoch 40 training [time: 15.94s, train loss: 13.8684]
Train    41: 100%|███████████████████████| 185/185 [00:15<00:00, 11.98it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:46    INFO  epoch 41 training [time: 15.45s, train loss: 13.3055]
Train    42: 100%|███████████████████████| 185/185 [00:15<00:00, 12.31it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:46    INFO  epoch 42 training [time: 15.03s, train loss: 12.6831]
Train    43: 100%|███████████████████████| 185/185 [00:15<00:00, 12.30it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:46    INFO  epoch 43 training [time: 15.04s, train loss: 12.2677]
Train    44: 100%|███████████████████████| 185/185 [00:14<00:00, 12.35it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:46    INFO  epoch 44 training [time: 14.99s, train loss: 11.7395]
Train    45: 100%|███████████████████████| 185/185 [00:15<00:00, 12.28it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:47    INFO  epoch 45 training [time: 15.07s, train loss: 11.2284]
Train    46: 100%|███████████████████████| 185/185 [00:15<00:00, 12.20it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:47    INFO  epoch 46 training [time: 15.16s, train loss: 10.7528]
Train    47: 100%|███████████████████████| 185/185 [00:15<00:00, 12.19it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:47    INFO  epoch 47 training [time: 15.18s, train loss: 10.3260]
Train    48: 100%|███████████████████████| 185/185 [00:15<00:00, 12.23it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:47    INFO  epoch 48 training [time: 15.12s, train loss: 9.8697]
Train    49: 100%|███████████████████████| 185/185 [00:15<00:00, 12.25it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:48    INFO  epoch 49 training [time: 15.10s, train loss: 9.5365]
Evaluate   : 100%|████████████████| 113592/113592 [02:45<00:00, 688.21it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:50    INFO  epoch 49 evaluating [time: 165.53s, valid_score: 0.052300]
08 Apr 23:50    INFO  valid result:
recall@10 : 0.0773    mrr@10 : 0.0452    ndcg@10 : 0.0523    hit@10 : 0.0796    precision@10 : 0.008
08 Apr 23:50    INFO  Saving current: saved/LightGCN-Apr-08-2026_23-24-12.pth
Train    50: 100%|███████████████████████| 185/185 [00:16<00:00, 11.21it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:51    INFO  epoch 50 training [time: 16.51s, train loss: 9.1484]
Train    51: 100%|███████████████████████| 185/185 [00:15<00:00, 12.01it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:51    INFO  epoch 51 training [time: 15.41s, train loss: 8.8030]
Train    52: 100%|███████████████████████| 185/185 [00:15<00:00, 12.24it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:51    INFO  epoch 52 training [time: 15.11s, train loss: 8.5362]
Train    53: 100%|███████████████████████| 185/185 [00:15<00:00, 12.30it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:51    INFO  epoch 53 training [time: 15.04s, train loss: 8.1590]
Train    54: 100%|███████████████████████| 185/185 [00:15<00:00, 12.32it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:52    INFO  epoch 54 training [time: 15.02s, train loss: 7.7974]
Train    55: 100%|███████████████████████| 185/185 [00:15<00:00, 12.27it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:52    INFO  epoch 55 training [time: 15.07s, train loss: 7.5587]
Train    56: 100%|███████████████████████| 185/185 [00:15<00:00, 12.24it/s, GPU RAM: 0.64 G/14.56 G]
08 Apr 23:52    INFO  epoch 56 training [time: 15.12s, train loss: 7.3513]

## Train SAE with saved LightGCN on Amazon Food

To evaluate the trained SAE model, you can add evaluation metrics after training.
Key metrics:

MSE Loss – reconstruction fidelity (lower is better)

L0 Norm – average sparsity (how many neurons fire per item)

Cosine Similarity – semantic preservation (closer to 1.0 is better)

Neuron Utilization – % of neurons that activate on at least one item

Activation Frequency – how evenly neurons are used across items

In [16]:
# Load existing SAE (retraining SAE) + interpret
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Apr-08-2026_23-24-12.pth \
    --item_category  "grocery and gourmet"  \
    --top_k 20 \
    --llm_model "meta-llama/Meta-Llama-3-8B-Instruct"

01:48:00  INFO      Run: LightGCN-Apr-08-2026_23-24-12   category: grocery and gourmet
01:48:00  INFO      ── Step 1: Loading base model ──────────────────
01:48:03  INFO      NumExpr defaulting to 2 threads.
2026-04-09 01:48:05.160085: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775699285.187101   54784 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775699285.194863   54784 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775699285.223981   54784 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699285.224021   54784 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699285.224027   54784 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699285.224032   54784 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-04-09 01:48:05.231846: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
01:48:11  INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery
checkpoint_dir = saved
show_progress = True
save_dataset = True
dataset_save_path = saved_data/
save_dataloaders = True
dataloaders_save_path = saved_dataloader/
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 30
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 2
reg_weight = 0.0001
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
01:48:18  INFO      Saving filtered dataset into [saved/amazon-grocery-Dataset.pth]
01:48:19  INFO      amazon-grocery
The number of users: 113593
Average actions of users: 8.854646453975633
The number of items: 39505
Average actions of items: 25.461143175374644
The number of inters: 1005817
The sparsity of the dataset: 99.97758620806647%
Remain Fields: ['user_id', 'item_id', 'timestamp']
01:48:32  INFO      Saving split dataloaders into: [saved/amazon-grocery-for-LightGCN-dataloader.pth]
01:49:22  INFO      [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
01:49:22  INFO      [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/model/general_recommender/lightgcn.py:126: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:654.)
  SparseL = torch.sparse.FloatTensor(i, data, torch.Size(L.shape))
01:50:00  INFO      Model=LightGCN uses=113593 items=39505  dim=64
01:50:00  WARNING   Item file not found: /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery/amazon-grocery.item  (only item_id will be available)
01:50:00  INFO      Item side-info loaded for 39504 items  (fields: ['title'])
Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 824, in <module>
    main()
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 566, in main
    with open(output_item_side_info, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: "./results/\x1b[1;35mamazon-grocery\x1b[0m\n\x1b[1;34mThe number of users\x1b[0m: 113593\n\x1b[1;34mAverage actions of users\x1b[0m: 8.854646453975633\n\x1b[1;34mThe number of items\x1b[0m: 39505\n\x1b[1;34mAverage actions of items\x1b[0m: 25.461143175374644\n\x1b[1;34mThe number of inters\x1b[0m: 1005817\n\x1b[1;34mThe sparsity of the dataset\x1b[0m: 99.97758620806647%\n\x1b[1;34mRemain Fields\x1b[0m: ['user_id', 'item_id', 'timestamp', 'neg_item_id']_item_side_info.json"

In [ ]:
import os

# The script expects data in: /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery.item
# But the error message suggests it might be checking a subfolder.
# Let's ensure the file is exactly where the RecBole data_path points.

corrected_out_dir = '/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery'
os.makedirs(corrected_out_dir, exist_ok=True)

output_item_path = os.path.join(corrected_out_dir, 'amazon-grocery.item')

# Use the export_df created earlier
export_df.to_csv(output_item_path, sep='\t', index=False)

print(f"File verified at: {output_item_path}")
!ls -l {output_item_path}

In [17]:
# Train SAE - LightGCN
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Apr-08-2026_23-24-12.pth \
    --item_category  "grocery and gourmet"  \
    --top_k 20 \
    --llm_model "meta-llama/Meta-Llama-3-8B-Instruct"

01:56:53  INFO      Run: LightGCN-Apr-08-2026_23-24-12   category: grocery and gourmet
01:56:53  INFO      ── Step 1: Loading base model ──────────────────
01:56:55  INFO      NumExpr defaulting to 2 threads.
2026-04-09 01:56:56.091491: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775699816.112531   57123 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775699816.119376   57123 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775699816.137088   57123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699816.137116   57123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699816.137120   57123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775699816.137124   57123 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-04-09 01:56:56.141804: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
01:57:03  INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery
checkpoint_dir = saved
show_progress = True
save_dataset = True
dataset_save_path = saved_data/
save_dataloaders = True
dataloaders_save_path = saved_dataloader/
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 30
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 2
reg_weight = 0.0001
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
01:57:08  INFO      Saving filtered dataset into [saved/amazon-grocery-Dataset.pth]
01:57:09  INFO      amazon-grocery
The number of users: 113593
Average actions of users: 8.854646453975633
The number of items: 39505
Average actions of items: 25.461143175374644
The number of inters: 1005817
The sparsity of the dataset: 99.97758620806647%
Remain Fields: ['user_id', 'item_id', 'timestamp']
01:57:19  INFO      Saving split dataloaders into: [saved/amazon-grocery-for-LightGCN-dataloader.pth]
01:58:02  INFO      [Training]: train_batch_size = [4096] train_neg_sample_args: [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}]
01:58:02  INFO      [Evaluation]: eval_batch_size = [4096] eval_args: [{'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}]
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/model/general_recommender/lightgcn.py:126: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:654.)
  SparseL = torch.sparse.FloatTensor(i, data, torch.Size(L.shape))
01:58:39  INFO      Model=LightGCN uses=113593 items=39505  dim=64
01:58:39  WARNING   Item file not found: /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery/amazon-grocery/amazon-grocery.item  (only item_id will be available)
01:58:39  INFO      Item side-info loaded for 39504 items  (fields: ['title'])
01:58:39  INFO      Object saved to ./results/amazon-grocery_item_side_info.json
device: cuda
01:58:39  INFO      ── Step 2: Training SAE ────────────────────────
01:58:39  INFO      Training SAE on BOTH user and item embeddings
01:58:39  INFO      Combined embeddings shape: (153098, 64)  (113593 users + 39505 items)
01:58:44  INFO      [SAE] epoch   1/200  loss=0.9045  recon=0.9045  aux=0.0000  dead=0.0%
01:59:49  INFO      [SAE] epoch  20/200  loss=0.3516  recon=0.3459  aux=0.1810  dead=51.3%
02:00:58  INFO      [SAE] epoch  40/200  loss=0.3189  recon=0.3137  aux=0.1658  dead=48.4%
02:02:08  INFO      [SAE] epoch  60/200  loss=0.3063  recon=0.3014  aux=0.1594  dead=44.8%
02:03:20  INFO      [SAE] epoch  80/200  loss=0.2994  recon=0.2945  aux=0.1566  dead=42.7%
02:04:32  INFO      [SAE] epoch 100/200  loss=0.2949  recon=0.2901  aux=0.1551  dead=41.5%
02:05:43  INFO      [SAE] epoch 120/200  loss=0.2918  recon=0.2870  aux=0.1531  dead=41.6%
02:07:00  INFO      [SAE] epoch 140/200  loss=0.2896  recon=0.2848  aux=0.1536  dead=40.5%
02:08:14  INFO      [SAE] epoch 160/200  loss=0.2876  recon=0.2828  aux=0.1532  dead=39.3%
02:09:25  INFO      [SAE] epoch 180/200  loss=0.2860  recon=0.2812  aux=0.1536  dead=38.3%
02:10:36  INFO      [SAE] epoch 200/200  loss=0.2846  recon=0.2799  aux=0.1525  dead=36.3%
02:10:36  INFO      [SAE] Saved → saved/LightGCN-Apr-08-2026_23-24-12-SAE.pth
02:10:36  INFO      SAE latent_dim=1024  k=8
02:10:36  INFO      ── Step 3: Encoding item embeddings through SAE ─
02:10:36  INFO      item_acts shape=(39505, 1024)  non-zero=0.8%
02:10:36  INFO      ── Step 3.5: Evaluating SAE ───────────────────
02:10:37  INFO      Reconstruction MSE: 0.120357
02:10:37  INFO      Avg sparsity (L0): 8.00 / 1024
02:10:37  INFO      Cosine similarity: 0.7662
02:10:37  INFO      Active neurons: 578/1024 (56.4%)
02:10:37  INFO      Neuron activation frequency: 0.78% (min=0.00%, max=31.79%)
02:10:37  INFO      ── Step 4: Ranking top items per neuron ────────
02:10:40  INFO      Active neurons (≥1 item): 578/1024  (dead: 446)
02:10:40  INFO      ── Step 5: LLM neuron labelling ────────────────
02:10:46  INFO      Loading HF model: meta-llama/Meta-Llama-3-8B-Instruct  (batch_size=32)
02:10:47  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json "HTTP/1.1 401 Unauthorized"
02:10:47  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/adapter_config.json "HTTP/1.1 401 Unauthorized"
02:10:47  INFO      HTTP Request: HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json "HTTP/1.1 401 Unauthorized"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_http.py", line 761, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/dist-packages/httpx/_models.py", line 829, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/hub.py", line 419, in cached_files
    hf_hub_download(
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 986, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1137, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1766, in _raise_on_head_call_error
    raise head_call_error
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1653, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 89, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1576, in get_hf_file_metadata
    response = _httpx_follow_relative_redirects_with_backoff(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_http.py", line 692, in _httpx_follow_relative_redirects_with_backoff
    hf_raise_for_status(response)
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_http.py", line 796, in hf_raise_for_status
    raise gated_err from e
huggingface_hub.errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-69d70aa7-2a6b6b60509490ac2be1fa89;00638097-4027-410f-b3ce-6b62a071a198)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 824, in <module>

  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 706, in main

  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 395, in _make_llm
    hf_batch = getattr(args, "hf_batch_size", 32)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole-SAE/run_neuron_interpret.py", line 332, in __init__
    logger.info(f"Loading HF model: {model_name}  (batch_size={hf_batch_size})")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/pipelines/__init__.py", line 734, in pipeline
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/models/auto/configuration_auto.py", line 1356, in from_pretrained
    config_dict, unused_kwargs = PreTrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/configuration_utils.py", line 569, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/configuration_utils.py", line 624, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/hub.py", line 276, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/utils/hub.py", line 483, in cached_files
    raise OSError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-69d70aa7-2a6b6b60509490ac2be1fa89;00638097-4027-410f-b3ce-6b62a071a198)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.

In [ ]:
# interpreting SAE with Llam
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Apr-08-2026_23-24-12.pth \
    --sae_checkpoint saved/LightGCN-Apr-08-2026_23-24-12-SAE.pth \
    --item_category  "grocery and gourmet"  \
    --top_k 20 \
    --llm_model "meta-llama/Meta-Llama-3-8B-Instruct"

02:34:27  INFO      Run: LightGCN-Apr-08-2026_23-24-12   category: grocery and gourmet
02:34:27  INFO      ── Step 1: Loading base model ──────────────────
02:34:33  INFO      NumExpr defaulting to 2 threads.
2026-04-09 02:34:52.824368: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775702092.856000   66845 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775702092.866169   66845 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775702092.903219   66845 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775702092.903244   66845 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775702092.903248   66845 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775702092.903253   66845 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-04-09 02:34:52.908235: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
02:35:26  INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 2020
state = INFO
reproducibility = True
data_path = /content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/dataset/amazon-grocery
checkpoint_dir = saved
show_progress = True
save_dataset = True
dataset_save_path = saved_data/
save_dataloaders = True
dataloaders_save_path = saved_dataloader/
log_wandb = False

Training Hyper Parameters:
epochs = 100
train_batch_size = 4096
learner = adam
learning_rate = 0.001
train_neg_sample_args = {'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}
eval_step = 10
stopping_step = 30
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'RS': [0.8, 0.1, 0.1]}, 'order': 'TO', 'group_by': 'user', 'mode': {'valid': 'full', 'test': 'full'}}
repeatable = False
metrics = ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk = [10]
valid_metric = NDCG@10
valid_metric_bigger = True
eval_batch_size = 4096
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'timestamp']}
unload_col = None
unused_col = None
additional_feat_suffix = None
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [0,inf)
item_inter_num_interval = [0,inf)
alias_of_user_id = None
alias_of_item_id = None
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = None
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id
benchmark_filename = None

Other Hyper Parameters:
worker = 0
wandb_project = recbole
shuffle = True
require_pow = False
enable_amp = False
enable_scaler = False
transform = None
embedding_size = 64
n_layers = 2
reg_weight = 0.0001
numerical_features = []
discretization = None
kg_reverse_r = False
entity_kg_num_interval = [0,inf)
relation_kg_num_interval = [0,inf)
MODEL_TYPE = ModelType.GENERAL
MODEL_INPUT_TYPE = InputType.PAIRWISE
eval_type = EvaluatorType.RANKING
single_spec = True
local_rank = 0
device = cuda
valid_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}
test_neg_sample_args = {'distribution': 'uniform', 'sample_num': 'none'}


/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:648: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
/content/drive/MyDrive/Colab_Notebooks/CIKMv3/RecBole/recbole/data/dataset/dataset.py:650: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
02:35:53  INFO      Saving filtered dataset into [saved/amazon-grocery-Dataset.pth]

In [ ]:
# Retry interpretation with the formatting fix
!python run_neuron_interpret.py \
    --checkpoint     saved/LightGCN-Apr-08-2026_23-24-12.pth \
    --sae_checkpoint saved/LightGCN-Apr-08-2026_23-24-12-SAE.pth \
    --item_category  "grocery and gourmet"  \
    --top_k 20 \
    --llm_model "meta-llama/Meta-Llama-3-8B-Instruct"